[package]
name = "launcher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
open = "4"
walkdir = "2"
path-absolutize = "3"
serde_json = "1.0.95"
serde = {version = "1", features = ["derive"]}
